import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:tracer/auth/auth_service.dart';

import 'auth_service_test.mocks.dart'; // generated by build_runner

// Tells Mockito to generate mocks for these classes
@GenerateMocks([SupabaseClient, GoTrueClient, Session, User])
void main() {
  late MockSupabaseClient mockSupabaseClient;
  late MockGoTrueClient mockGoTrueClient;
  late AuthService authService;

  // Runs before each test — sets up fresh mocks every time
  setUp(() {
    mockSupabaseClient = MockSupabaseClient();
    mockGoTrueClient = MockGoTrueClient();
    authService = AuthService(mockSupabaseClient);

    // Tell the mock SupabaseClient to return our mock GoTrueClient
    // when .auth is accessed
    when(mockSupabaseClient.auth).thenReturn(mockGoTrueClient);
  });

  group('AuthService Tests', () {

    // --- logIn Tests ---
    group('logIn', () {
      test('should return AuthResponse on successful login', () async {
        final mockResponse = AuthResponse(session: MockSession(), user: MockUser());

        when(mockGoTrueClient.signInWithPassword(
          email: 'test@email.com',
          password: 'password123',
        )).thenAnswer((_) async => mockResponse);

        final result = await authService.logIn('test@email.com', 'password123');

        expect(result, isA<AuthResponse>());
        verify(mockGoTrueClient.signInWithPassword(
          email: 'test@email.com',
          password: 'password123',
        )).called(1);
      });

      test('should throw exception on failed login', () async {
        when(mockGoTrueClient.signInWithPassword(
          email: anyNamed('email'),
          password: anyNamed('password'),
        )).thenThrow(AuthException('Invalid login credentials'));

        expect(
          () async => await authService.logIn('wrong@email.com', 'wrongpassword'),
          throwsA(isA<AuthException>()),
        );
      });
    });

    // --- signUp Tests ---
    group('signUp', () {
      test('should return AuthResponse on successful sign up', () async {
        final mockResponse = AuthResponse(session: null, user: MockUser());

        when(mockGoTrueClient.signUp(
          email: 'newuser@email.com',
          password: 'newpassword123',
          emailRedirectTo: anyNamed('emailRedirectTo'),
        )).thenAnswer((_) async => mockResponse);

        final result = await authService.signUp('newuser@email.com', 'newpassword123');

        expect(result, isA<AuthResponse>());
        verify(mockGoTrueClient.signUp(
          email: 'newuser@email.com',
          password: 'newpassword123',
          emailRedirectTo: anyNamed('emailRedirectTo'),
        )).called(1);
      });

      test('should throw exception if email already in use', () async {
        when(mockGoTrueClient.signUp(
          email: anyNamed('email'),
          password: anyNamed('password'),
          emailRedirectTo: anyNamed('emailRedirectTo'),
        )).thenThrow(AuthException('User already registered'));

        expect(
          () async => await authService.signUp('existing@email.com', 'password123'),
          throwsA(isA<AuthException>()),
        );
      });
    });

    // --- logOut Tests ---
    group('logOut', () {
      test('should call signOut once', () async {
        when(mockGoTrueClient.signOut()).thenAnswer((_) async {});

        await authService.logOut();

        verify(mockGoTrueClient.signOut()).called(1);
      });
    });

    // --- getCurrentUserEmail Tests ---
    group('getCurrentUserEmail', () {
      test('should return email when session exists', () {
        final mockSession = MockSession();
        final mockUser = MockUser();

        when(mockGoTrueClient.currentSession).thenReturn(mockSession);
        when(mockSession.user).thenReturn(mockUser);
        when(mockUser.email).thenReturn('test@email.com');

        final result = authService.getCurrentUserEmail();

        expect(result, 'test@email.com');
      });

      test('should return null when no session exists', () {
        when(mockGoTrueClient.currentSession).thenReturn(null);

        final result = authService.getCurrentUserEmail();

        expect(result, isNull);
      });
    });
  });
}